/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zsshen_dexfilehunter_DexFileHunter */

#ifndef _Included_org_zsshen_dexfilehunter_DexFileHunter
#define _Included_org_zsshen_dexfilehunter_DexFileHunter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zsshen_dexfilehunter_DexFileHunter
 * Method:    ScanMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zsshen_dexfilehunter_DexFileHunter_ScanMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
